# Generated by Django 3.2.16 on 2022-12-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_following_pair_unique',
        ),
    ]
