# Generated by Django 3.2.16 on 2022-12-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_follow_user_following_pair_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='user_following_pair_unique'),
        ),
    ]
